name: Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image

    - uses: docker/login-action@v1 
      name: Login to DockerHub
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/build-push-action@v2
      name: Build and push
      id: docker_build
      with:
        push: true
        tags: oneprocloud/cloud-discovery-prophet:latest
